[connections.geminiapi]
GEMINI_API_KEY = "" #Enter your Gemini API Key
[connections.datafoods]
spreadsheet = "https://docs.google.com/spreadsheets/d/1mPr8Q43p4JtaoEUaf5cIK4sR_af2A2amT_rcT9SaHKY/edit?usp=sharing"
